POST http://localhost:4000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###

POST http://localhost:4000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

GET http://localhost:4000/user/tweets/feed/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

###

GET http://localhost:4000/user/following/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

###

GET http://localhost:4000/user/followers/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

###
GET http://localhost:4000/tweets/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

###
GET http://localhost:4000/tweets/10/likes/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

###

GET http://localhost:4000/tweets/10/replies/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

###

GET http://localhost:4000/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

###
POST http://localhost:4000/user/tweets/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM

{
   "tweet": "The Mornings is like heaven..."
}

###
DELETE http://localhost:4000/tweets/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjgxMjc2MjU0fQ.rRaoHllswM14EWG8e4TKhN3hmbxQaTYzEthvZpioUHM